version: "3.3"
services:
  ptouch-web:
    build: .
    ports:
      - 8080:8080
    devices:
#      - /dev/rfcomm0
      - /dev/bus/usb
    volumes:
      - ./recents.db:/app/recents.db
#    command: /app/ptouch-web /dev/rfcomm0
    command: /app/ptouch-web usb
    restart: always