services:
  ptouch-web:
    build: .
    ports:
      - 8080:8080
    devices:
#      - /dev/rfcomm0
      - /dev/bus/usb
    volumes:
      - ./recents/:/app/recents
      - ./static/:/app/static
#    command: /app/ptouch-web /dev/rfcomm0
    command: /app/ptouch-web usb
    restart: always
